import { Inter } from "next/font/google";
import Providers from "../Provider.jsx";
import { getDictionary } from "../getDictionary";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const lang = await getDictionary(params.lang);
  return (
    <html lang={params.lang} className="light" style={{ colorScheme: "light" }}>
      <head>
        <title>F8 portfolio</title>
      </head>
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
