CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar(200) NOT NULL,
  "price" float,
  "detail" text NOT NULL,
  "teacher_id" int NOT NULL,
  "active" int,
  "created_at" timesamp,
  "updated_at" timestamp
);

CREATE TABLE "teacher" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar(200),
  "bio" text,
  "created_at" timesamp,
  "updated_at" timestamp
);

ALTER TABLE "courses" ADD FOREIGN KEY ("teacher_id") REFERENCES "teacher" ("id");
