import Navigation from "@/components/Navigation";

export const metadata = {
  title: "F8 - học lap trinh ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <main>
          {/* <Navigation /> */}
          {children}
        </main>
      </body>
    </html>
  );
}
